# Generated by Django 2.1.5 on 2019-01-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sss',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
