# Generated by Django 2.0 on 2019-01-14 22:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.IntegerField(verbose_name='Posta Kodu')),
                ('adres', models.TextField()),
                ('name', models.CharField(max_length=70, verbose_name='Adınız')),
                ('last_name', models.CharField(max_length=70)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Telefon numarası şu şekilde girilmelidir: '+999999999'. 15 haneye kadar izin verilir.", regex='^\\+?1?\\d{9,15}$')])),
                ('mail', models.EmailField(max_length=80)),
                ('adres_name', models.CharField(help_text='Adres Adı Örn : Evim', max_length=50, verbose_name='Adres Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Cargo')),
                ('delivery_time', models.CharField(max_length=50)),
                ('price', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_p', models.ManyToManyField(to='product.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='İlçe')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.City')),
            ],
        ),
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('sepet_no', models.CharField(blank=True, max_length=15, null=True)),
                ('sepet_tutar', models.DecimalField(decimal_places=2, max_digits=9)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SepetUrunler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.SmallIntegerField()),
                ('attr', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=9)),
                ('details', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('parent_sepet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Sepet')),
            ],
        ),
        migrations.CreateModel(
            name='TamSiparisler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mail', models.CharField(max_length=50)),
                ('adres_text', models.TextField()),
                ('product_text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Cargo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_sepet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Sepet')),
            ],
        ),
        migrations.AddField(
            model_name='adress',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.City'),
        ),
        migrations.AddField(
            model_name='adress',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Province', verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='adress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
