# Generated by Django 2.0 on 2019-01-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='town',
            new_name='province',
        ),
    ]
