# Generated by Django 2.0 on 2019-01-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190115_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepet',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=None, to='account.Cargo'),
            preserve_default=False,
        ),
    ]
