# Generated by Django 2.0 on 2019-01-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190115_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sepet',
            name='totalWithCoupon',
        ),
        migrations.AlterField(
            model_name='sepet',
            name='sepet_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
