# Generated by Django 2.0 on 2019-01-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190115_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepet',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='account.Cargo'),
        ),
    ]
