# Generated by Django 2.0 on 2019-01-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190125_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepet',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=None, to='account.Cargo'),
            preserve_default=False,
        ),
    ]
