# Generated by Django 2.1.5 on 2019-01-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayarlar', '0003_sitesettings_adres'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mail',
            field=models.CharField(default=1, max_length=100, verbose_name='E-mail Adresiniz'),
            preserve_default=False,
        ),
    ]
