# Generated by Django 2.0 on 2019-01-14 22:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaings', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='brands')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Dosya Başlık')),
                ('image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Ürün Adı')),
                ('info', ckeditor.fields.RichTextField()),
                ('code', models.CharField(default='542323', editable=False, max_length=150, verbose_name='Ürün Kodu')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('stock', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True, verbose_name='link')),
                ('image', models.ImageField(upload_to='product', verbose_name='Ana Resim')),
                ('tags', models.CharField(blank=True, help_text='Lütfen kelimelerin arasında virgül kullanınız ve boşluk kullanmayınız', max_length=200, null=True)),
                ('disc_price', models.DecimalField(blank=True, decimal_places=2, help_text='İndirim eklemek istemiyorsanız boş kalsın', max_digits=20, null=True, verbose_name='İndirimli Fiyat')),
                ('voteAverage', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Brands')),
                ('disc_group', models.ForeignKey(blank=True, default=0, null=True, on_delete=None, to='campaings.Campaign')),
                ('main_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.AnaMenu')),
                ('sub_menu', smart_selects.db_fields.ChainedForeignKey(chained_field='main_menu', chained_model_field='parent', on_delete=django.db.models.deletion.CASCADE, to='home.AltMenu')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Attr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='SubDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.SmallIntegerField()),
                ('qty', models.SmallIntegerField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('sub_details', models.ManyToManyField(to='product.Sub_Attr')),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='detail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='detail',
            name='sub_attr',
            field=models.ManyToManyField(blank=True, null=True, to='product.Sub_Attr'),
        ),
    ]
