# Generated by Django 2.0 on 2019-01-14 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Kampanya Adı')),
                ('discPercentage', models.SmallIntegerField(default=0, help_text='İndirim Yüzdesi', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
                ('active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(verbose_name='Kampanya Başlangıç')),
                ('last_date', models.DateTimeField(verbose_name='Kampanya bitiş')),
            ],
        ),
    ]
