# Generated by Django 2.0 on 2019-01-23 10:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='banner',
            field=models.ImageField(default=datetime.datetime(2019, 1, 23, 10, 14, 34, 177790, tzinfo=utc), upload_to='campaignBanner'),
            preserve_default=False,
        ),
    ]
