# Generated by Django 2.0 on 2019-01-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0002_campaign_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='campaignBanner'),
        ),
    ]
