# Generated by Django 2.1.5 on 2019-01-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190130_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, help_text='Lütfen kelimelerin arasında virgül kullanınız ve boşluk kullanmayınız', max_length=200, null=True),
        ),
    ]
