# Generated by Django 2.0 on 2019-01-14 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AltMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Menü başlık')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='link')),
                ('active', models.BooleanField(default=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='menu_banner')),
                ('label_types', models.CharField(blank=True, choices=[('HOT', 'HOT'), ('NEW', 'NEW'), ('SALE', 'SALE')], max_length=12, null=True, verbose_name='Etiket')),
            ],
            options={
                'verbose_name_plural': 'Alt Menüler',
            },
        ),
        migrations.CreateModel(
            name='AnaMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Menü başlık')),
                ('slug', models.SlugField(unique=True, verbose_name='link')),
                ('active', models.BooleanField(default=True)),
                ('banner', models.ImageField(upload_to='menu_banner')),
            ],
            options={
                'verbose_name_plural': 'Ana Menüler',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=150)),
                ('sub_slogan', models.CharField(max_length=150, verbose_name='Alt slogan')),
                ('image', models.ImageField(upload_to='banner', verbose_name='Banner')),
            ],
        ),
        migrations.AddField(
            model_name='altmenu',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.AnaMenu'),
        ),
    ]
