# Generated by Django 2.0 on 2019-01-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hedef Url'),
        ),
    ]
