# Generated by Django 2.1.5 on 2019-01-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomments',
            name='votes',
        ),
    ]
