# Generated by Django 2.1.5 on 2019-01-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_remove_blogcomments_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
